Edgeworn/additions
DevYukine/red_oxide pull request #6
Opened 2023-07-22 16:26 UTC by edgeworn

2023-07-22 16:26 UTC, edgeworn commented
sorry wrong repo

2023-07-24 13:32 UTC, DevYukine requested changes
I overall like these changes but i think instead adding a `spectrogram_only` flag we should move that to an own subcommand as its really out of scope for "transcode" if you only want to create spectrograms anyway, could you please move that change out of this PR into a new one implementing it as a new subcommand?

The other small changes/bugfixes are (after my suggested changes) good to merge without the flag 👍

2023-07-24 13:32 UTC, DevYukine commented on src/main.rs
> +        match result {
Could you instead not handling success and handling error just check for error with 
```Rust
if let Err(e) = result {
}
```

2023-07-24 13:32 UTC, DevYukine commented on src/main.rs
> +    let base_name = raw_base_name.replace(&['<', '>', ':', '"', '/', '\\', '|', '?', '*', '/'][..], "_");
please move this to src/redacted/api/constants.rs and make it a constant

2023-07-24 14:42 UTC, edgeworn commented
Thanks for the comments! I probably won't have time until the weekend but I'll address them soon

2023-07-28 15:06 UTC, edgeworn commented
updated, thank you! i'll make a follow up to add a `generate_spectrograms` command

2023-08-04 11:20 UTC, DevYukine approved these changes

2023-08-04 11:22 UTC, DevYukine commented
This fixes #4

2023-08-04 11:22 UTC, merged